DROP FUNCTION IF EXISTS select_all_leagues();
DROP FUNCTION IF EXISTS select_league_by_id(BIGINT);
DROP FUNCTION IF EXISTS insert_league(VARCHAR(100));
DROP FUNCTION IF EXISTS delete_league(BIGINT);
DROP FUNCTION IF EXISTS update_league(BIGINT, VARCHAR(100));

DROP TABLE IF EXISTS bet;
DROP TABLE IF EXISTS person;
DROP TABLE IF EXISTS offer;
DROP TABLE IF EXISTS event;
DROP TABLE IF EXISTS league;